services:
  sharx:
    image: registry.konstpic.ru/3x-ui/3xui:3.0.0b
    container_name: sharx_app
    # hostname: yourhostname
    ports:
      - "2053:2053"   # Web UI
      - "2096:2096"   # Subscriptions
    #   - "443:443"     # Inbound
    volumes:
      - $PWD/cert/:/app/cert/
    environment:
      # Xray settings
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_ENABLE_FAIL2BAN: "true"
      # XUI_LOG_LEVEL: "debug"
      
      # Web Panel настройки (только через env, не доступны в UI)
      # XUI_WEB_PORT: 2053
      # XUI_WEB_LISTEN: 0.0.0.0
      # XUI_WEB_DOMAIN: panel.example.com
      # XUI_WEB_BASE_PATH: /
      # XUI_WEB_CERT_FILE: /app/cert/fullchain.pem
      # XUI_WEB_KEY_FILE: /app/cert/privkey.pem
      
      # Subscription настройки (только через env, не доступны в UI)
      # XUI_SUB_PORT: 2096
      # XUI_SUB_PATH: /sub/
      # XUI_SUB_DOMAIN: sub.example.com
      # XUI_SUB_CERT_FILE: /app/cert/sub-fullchain.pem
      # XUI_SUB_KEY_FILE: /app/cert/sub-privkey.pem
      
      # PostgreSQL settings
      XUI_DB_HOST: postgres
      XUI_DB_PORT: 5432
      XUI_DB_USER: xui_user
      XUI_DB_PASSWORD: change_this_password
      XUI_DB_NAME: xui_db
      XUI_DB_SSLMODE: disable
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sharx_network
    tty: true
#    network_mode: host
    restart: unless-stopped

  postgres:
    image: registry.konstpic.ru/3x-ui/postgres:16-alpine
    container_name: sharx_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: xui_user
      POSTGRES_PASSWORD: change_this_password
      POSTGRES_DB: xui_db
    volumes:
      - $PWD/postgres_data:/var/lib/postgresql/data
    networks:
      - sharx_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -p 5432 -U xui_user -d xui_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  sharx_network:
    driver: bridge
